ALTER TABLE DOOS.I18N_CODES   ALTER CODE_ID   SET DEFAULT NEXTVAL('DOOS.SEQ_I18N_CODES'::REGCLASS);
ALTER TABLE DOOS.I18N_LIJSTEN ALTER LIJST_ID  SET DEFAULT NEXTVAL('DOOS.SEQ_I18N_LIJSTEN'::REGCLASS);

ALTER SEQUENCE DOOS.SEQ_I18N_CODES    OWNER TO DOOS;
ALTER SEQUENCE DOOS.SEQ_I18N_CODES    INCREMENT 1;
ALTER SEQUENCE DOOS.SEQ_I18N_LIJSTEN  OWNER TO DOOS;
ALTER SEQUENCE DOOS.SEQ_I18N_LIJSTEN  INCREMENT 1;
