-- Invoer van Talen in het DOOS schema.
-- 
-- Copyright 2012 Marco de Booij
--
-- Licensed under the EUPL, Version 1.1 or - as soon they will be approved by
-- the European Commission - subsequent versions of the EUPL (the "Licence");
-- you may not use this work except in compliance with the Licence. You may
-- obtain a copy of the Licence at:
--
-- http://www.osor.eu/eupl
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the Licence is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the Licence for the specific language governing permissions and
-- limitations under the Licence.
--
-- Project: DOOS
-- Author: Marco de Booij

insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Onbekend', 'Onbekend', '??');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Afaraf', 'Afar, Hamitisch', 'aa');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Аҧсуа', 'Abchazisch', 'ab');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Avesta', 'Avestisch', 'ae');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Afrikaans', 'Afrikaans', 'af');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Akan', 'Akan', 'ak');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('አማርኛ', 'Amhaars, Amharisch', 'am');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Aragonés', 'Aragonees', 'an');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('العربية', 'Arabisch', 'ar');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('অসমীয়া', 'Assamees, Assami', 'as');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('авар мацӀ', 'Avaars', 'av');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('aymar aru', 'Aymara, Aymará', 'ay');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('azərbaycan dili', 'Azerbeidzjaans, Azeri', 'az');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('башҡорт теле', 'Basjkiers, Basjkirisch', 'ba');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Беларуская', 'Wit-Russisch, Belarussisch', 'be');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('български език', 'Bulgaaars', 'bg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('भोजपुरी', 'Bihari', 'bh');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Bislama', 'Bislama', 'bi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('bamanankan', 'Bambara', 'bm');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('বাংলা', 'Bengaaals', 'bn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('བོད་ཡིག', 'Tibetaans', 'bo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('brezhoneg', 'Bretons', 'br');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('bosanski jezik', 'Bosnisch', 'bs');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Català', 'Catalaans', 'ca');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('нохчийн мотт', 'Tsjetsjeens', 'ce');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Chamoru', 'Chamorro', 'ch');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('corsu', 'Corsicaans', 'co');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ᓀᐦᐃᔭᐍᐏᐣ', 'Cree', 'cr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('česky', 'Tsjechisch', 'cs');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ѩзыкъ словѣньскъ', 'Kerkslavisch', 'cu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('чӑваш чӗлхи', 'Tsjoevasjisch', 'cv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Cymraeg', 'Welsh', 'cy');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('dansk', 'Deens', 'da');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Deutsch', 'Duits', 'de');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ދިވެހި', 'Divehi', 'dv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('རྫོང་ཁ', 'Dzongkha', 'dz');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ɛʋɛgbɛ', 'Ewe', 'ee');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ελληνικά', 'Grieks', 'el');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('English', 'Engels', 'en');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Esperanto', 'Esperanto', 'eo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('español', 'Spaans', 'es');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Eesti keel', 'Estisch', 'et');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('euskara', 'Baskisch', 'eu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('فارسی', 'Perzisch', 'fa');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('suomen kieli', 'Fins', 'fi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('vosa Vakaviti', 'Fijisch', 'fj');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Føroyskt', 'Faeröers', 'fo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('français', 'Frans', 'fr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Frysk', 'Fries', 'fy');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Gaeilge', 'Iers-Gaelisch', 'ga');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Gàidhlig', 'Schots-Gaelisch', 'gd');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Galego', 'Galicisch', 'gl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Avañe''ẽ', 'Guaraní', 'gn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ગુજરાતી', 'Gujarati', 'gu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ghaelg', 'Manx-Gaelisch', 'gv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('هَوُسَ', 'Hausa', 'ha');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('עברית', 'Hebreeuws', 'he');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('हिन्दी, हिंदी', 'Hindi', 'hi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Hiri Motu', 'Hiri Motu', 'ho');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Hrvatski', 'Kroatisch', 'hr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kreyòl ayisyen', 'Kreyòl', 'ht');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Magyar', 'Hongaars', 'hu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Հայերեն', 'Armeens', 'hy');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Otjiherero', 'Herero', 'hz');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Interlingua', 'Interlingua', 'ia');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Bahasa Indonesia', 'Indonesisch', 'id');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Interlingue', 'Interlingue', 'ie');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Igbo', 'Igbo', 'ig');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ꆇꉙ', 'Yi', 'ii');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Inupiak', 'Inupiak', 'ik');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ido', 'Ido', 'io');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Íslenska', 'IJslands', 'is');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Italiano', 'Italiaans', 'it');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ᐃᓄᒃᑎᑐᑦ', 'Inuktitut', 'iu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('日本語', 'Japans', 'ja');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Basa Jawa', 'Javaans', 'jw');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ქართული', 'Georgisch', 'ka');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('KiKongo', 'Kikongo', 'kg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Gĩkũyũ', 'Gikuyu', 'ki');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kuanyama', 'Kwanyama', 'kj');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Қазақ тілі', 'Kazachs', 'kk');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('kalaallisut', 'Groenlands', 'kl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ភាសាខ្មែរ', 'Khmer', 'km');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ಕನ್ನಡ', 'Kannada', 'kn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('한국어', 'Koreaans', 'ko');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kanuri', 'Kanuri', 'kr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('कश्मीरी', 'Kasjmiri', 'ks');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('كوردی', 'Koerdisch', 'ku');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('коми кыв', 'Zurjeens', 'kv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Cornish', 'Cornisch', 'kw');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('кыргыз тили', 'Kirgizisch', 'ky');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('latine', 'Latijn', 'la');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Lëtzebuergesch', 'Luxemburgs', 'lb');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Luganda', 'Luganda', 'lg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Limburgs', 'Limburgs', 'li');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Lingála', 'Lingala', 'ln');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ພາສາລາວ', 'Laotiaans', 'lo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('lietuvių kalba', 'Litouws', 'lt');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Luba-Katanga', 'Luba-Katanga', 'lu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('latviešu valoda', 'Lets', 'lv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Malagasy fiteny', 'Plateaumalagasi', 'mg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kajin M̧ajeļ', 'Marshallees', 'mh');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Te Reo Māori', 'Maori', 'mi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('македонски јазик', 'Macedonisch', 'mk');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('മലയാളം', 'Malayalam', 'ml');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Монгол', 'Mongools', 'mn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('лимба молдовеняскэ', 'Moldavisch', 'mo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('मराठी', 'Marathi', 'mr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('بهاس ملايو', 'Maleis', 'ms');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Malti', 'Maltees', 'mt');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ဗမာစာ', 'Birmaans', 'my');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ekakairũ Naoero', 'Nauruaans', 'na');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Norsk bokmål', 'Norwegian Bokmål', 'nb');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('isiNdebele', 'Noord-Ndebele', 'nd');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('नेपाली', 'Nepalees', 'ne');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Owambo', 'Ndonga', 'ng');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Nederlands', 'Nederlands', 'nl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Norsk nynorsk', 'Nynorsk', 'nn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Norsk', 'Noors', 'no');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ndébélé', 'Zuid-Ndebele', 'nr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Diné bizaad', 'Navajo', 'nv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('chiCheŵa', 'Nyanja', 'ny');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Occitan', 'Occitaans', 'oc');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ᐊᓂᔑᓈᐯᒧᐎᓐ', 'Ojibweg', 'oj');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Afaan Oromoo', 'Afaan Oromoo', 'om');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ଓଡ଼ିଆ', 'Oriya', 'or');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Ирон æвзаг', 'Ossetisch', 'os');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ਪੰਜਾਬੀ', 'Punjabi', 'pa');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('पािऴ', 'Pali', 'pi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('język polski', 'Pools', 'pl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('پښتو', 'Pasjtoe', 'ps');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Português', 'Portugees', 'pt');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Quechua', 'Quechua', 'qu');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('rumantsch grischun', 'Reto-Romaans', 'rm');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('kiRundi', 'Kirundi', 'rn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Română', 'Roemeens', 'ro');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('русский язык', 'Russisch', 'ru');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kinyarwanda', 'Kinyarwanda', 'rw');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('संस्कृतम्', 'Sanskriet', 'sa');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('sardu', 'Sardijns', 'sc');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('सिन्धी', 'Sindhi', 'sd');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Davvisámegiella', 'Noord-Samisch', 'se');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('yângâ tî sängö', 'Sangho', 'sg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Српскохрватски', 'Servo-Kroatisch', 'sh');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('සිංහල', 'Singalees', 'si');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('slovenčina', 'Slowaaks', 'sk');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('slovenščina', 'Sloveens', 'sl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('gagana fa''a Samoa', 'Samoaans', 'sm');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('chiShona', 'Shona', 'sn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Soomaaliga', 'Somalisch', 'so');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Shqip', 'Albanees', 'sq');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('српски језик', 'Servisch', 'sr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('SiSwati', 'Swasi', 'ss');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('seSotho', 'Zuid-Sotho', 'st');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Basa Sunda', 'Sundanees', 'su');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Svenska', 'Zweeds', 'sv');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Kiswahili', 'Swahili', 'sw');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('தமிழ்', 'Tamil', 'ta');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('తెలుగు', 'Telugu', 'te');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('тоҷикӣ', 'Tadzjieks', 'tg');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ไทย', 'Thai', 'th');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ትግርኛ ፊደል', 'Tigrinya', 'ti');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Türkmen', 'Turkmeens', 'tk');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Tagalog', 'Tagalog', 'tl');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('seTswana', 'Tswana', 'tn');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('faka Tonga', 'Tongaans', 'to');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Türkçe', 'Turks', 'tr');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('xiTsonga', 'Tsonga', 'ts');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Tataтатарча', 'Tataars', 'tt');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Twi', 'Twi', 'tw');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Reo Tahiti', 'Tahitiaans', 'ty');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Uyƣurqə', 'Oeigoers', 'ug');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('українська мова', 'Oekraïens', 'uk');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('اردو', 'Urdu', 'ur');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('O''zbek', 'Oezbeeks', 'uz');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('tshiVenḓa', 'Venda', 've');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Tiếng Việt', 'Vietnamees', 'vi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Volapük', 'Volapük', 'vo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Walon', 'Waals', 'wa');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Wollof', 'Wolof', 'wo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('isiXhosa', 'Xhosa', 'xh');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('ייִדיש', 'Jiddish', 'yi');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Yorùbá', 'Yoruba', 'yo');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('Saɯ cueŋƅ', 'Zhuang', 'za');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('中文', 'Chinees', 'zh');
insert into DOOS.TALEN (EIGENNAAM, TAAL, TAAL_KODE) values('isiZulu', 'Zoeloe', 'zu');
COMMIT;
